// <auto-generated />
using System;
using BikeRental.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRental.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(BikeRentalDbContext))]
    [Migration("20251205192843_AddData")]
    partial class AddData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BikeRental.Domain.Models.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Bike", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Красный",
                            ModelId = 1,
                            SerialNumber = "SN1001"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Чёрный",
                            ModelId = 2,
                            SerialNumber = "SN1002"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Белый",
                            ModelId = 3,
                            SerialNumber = "SN1003"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Синий",
                            ModelId = 4,
                            SerialNumber = "SN1004"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Зелёный",
                            ModelId = 5,
                            SerialNumber = "SN1005"
                        },
                        new
                        {
                            Id = 6,
                            Color = "Жёлтый",
                            ModelId = 6,
                            SerialNumber = "SN1006"
                        },
                        new
                        {
                            Id = 7,
                            Color = "Серый",
                            ModelId = 7,
                            SerialNumber = "SN1007"
                        },
                        new
                        {
                            Id = 8,
                            Color = "Оранжевый",
                            ModelId = 8,
                            SerialNumber = "SN1008"
                        },
                        new
                        {
                            Id = 9,
                            Color = "Фиолетовый",
                            ModelId = 9,
                            SerialNumber = "SN1009"
                        },
                        new
                        {
                            Id = 10,
                            Color = "Розовый",
                            ModelId = 10,
                            SerialNumber = "SN1010"
                        });
                });

            modelBuilder.Entity("BikeRental.Domain.Models.BikeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BikeWeight")
                        .HasColumnType("float");

                    b.Property<string>("BrakeType")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("HourlyPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("MaxRiderWeight")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WheelSize")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BikeModel", null, t =>
                        {
                            t.HasCheckConstraint("CK_BikeModels_HourlyPrice", "[HourlyPrice] > 0");

                            t.HasCheckConstraint("CK_BikeModels_MaxRiderWeight", "[MaxRiderWeight] > 0");

                            t.HasCheckConstraint("CK_BikeModels_WheelSize", "[WheelSize] > 0");

                            t.HasCheckConstraint("CK_BikeModels_Year", "[Year] IS NULL OR ([Year] >= 1900 AND [Year] <= 2100)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BikeWeight = 9.0,
                            BrakeType = "Caliper",
                            HourlyPrice = 150m,
                            MaxRiderWeight = 100.0,
                            Type = 0,
                            WheelSize = 28,
                            Year = 2021
                        },
                        new
                        {
                            Id = 2,
                            BikeWeight = 13.0,
                            BrakeType = "Disc",
                            HourlyPrice = 180m,
                            MaxRiderWeight = 110.0,
                            Type = 1,
                            WheelSize = 29,
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            BikeWeight = 14.0,
                            BrakeType = "Drum",
                            HourlyPrice = 100m,
                            MaxRiderWeight = 120.0,
                            Type = 2,
                            WheelSize = 26,
                            Year = 2019
                        },
                        new
                        {
                            Id = 4,
                            BikeWeight = 22.0,
                            BrakeType = "Disc",
                            HourlyPrice = 400m,
                            MaxRiderWeight = 120.0,
                            Type = 3,
                            WheelSize = 27,
                            Year = 2022
                        },
                        new
                        {
                            Id = 5,
                            BikeWeight = 8.0,
                            BrakeType = "V-Brake",
                            HourlyPrice = 60m,
                            MaxRiderWeight = 60.0,
                            Type = 4,
                            WheelSize = 20,
                            Year = 2023
                        },
                        new
                        {
                            Id = 6,
                            BikeWeight = 13.0,
                            BrakeType = "Disc",
                            HourlyPrice = 160m,
                            MaxRiderWeight = 105.0,
                            Type = 1,
                            WheelSize = 27,
                            Year = 2018
                        },
                        new
                        {
                            Id = 7,
                            BikeWeight = 15.0,
                            BrakeType = "Coaster",
                            HourlyPrice = 95m,
                            MaxRiderWeight = 130.0,
                            Type = 2,
                            WheelSize = 28,
                            Year = 2017
                        },
                        new
                        {
                            Id = 8,
                            BikeWeight = 8.0,
                            BrakeType = "Disc",
                            HourlyPrice = 220m,
                            MaxRiderWeight = 95.0,
                            Type = 0,
                            WheelSize = 28,
                            Year = 2024
                        },
                        new
                        {
                            Id = 9,
                            BikeWeight = 25.0,
                            BrakeType = "Hydraulic Disc",
                            HourlyPrice = 450m,
                            MaxRiderWeight = 125.0,
                            Type = 3,
                            WheelSize = 26,
                            Year = 2021
                        },
                        new
                        {
                            Id = 10,
                            BikeWeight = 7.0,
                            BrakeType = "Coaster",
                            HourlyPrice = 50m,
                            MaxRiderWeight = 40.0,
                            Type = 4,
                            WheelSize = 16,
                            Year = 2020
                        });
                });

            modelBuilder.Entity("BikeRental.Domain.Models.RentalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BikeId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("RenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("RenterId");

                    b.HasIndex("StartTime");

                    b.ToTable("RentalRecord", null, t =>
                        {
                            t.HasCheckConstraint("CK_RentalRecords_Duration", "[Duration] > '00:00:00'");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BikeId = 1,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = 1,
                            StartTime = new DateTime(2023, 12, 2, 7, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BikeId = 2,
                            Duration = new TimeSpan(0, 4, 0, 0, 0),
                            RenterId = 2,
                            StartTime = new DateTime(2023, 12, 7, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BikeId = 3,
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            RenterId = 3,
                            StartTime = new DateTime(2023, 12, 12, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            BikeId = 4,
                            Duration = new TimeSpan(0, 6, 0, 0, 0),
                            RenterId = 4,
                            StartTime = new DateTime(2023, 12, 14, 4, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            BikeId = 5,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = 5,
                            StartTime = new DateTime(2023, 12, 17, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            BikeId = 6,
                            Duration = new TimeSpan(0, 5, 0, 0, 0),
                            RenterId = 6,
                            StartTime = new DateTime(2023, 12, 20, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            BikeId = 7,
                            Duration = new TimeSpan(0, 7, 0, 0, 0),
                            RenterId = 7,
                            StartTime = new DateTime(2023, 12, 22, 3, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            BikeId = 8,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = 8,
                            StartTime = new DateTime(2023, 12, 23, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            BikeId = 9,
                            Duration = new TimeSpan(0, 8, 0, 0, 0),
                            RenterId = 9,
                            StartTime = new DateTime(2023, 12, 25, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            BikeId = 10,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = 10,
                            StartTime = new DateTime(2023, 12, 26, 7, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            BikeId = 2,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = 1,
                            StartTime = new DateTime(2023, 12, 27, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            BikeId = 2,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = 2,
                            StartTime = new DateTime(2023, 12, 28, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            BikeId = 1,
                            Duration = new TimeSpan(0, 4, 0, 0, 0),
                            RenterId = 3,
                            StartTime = new DateTime(2023, 12, 29, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            BikeId = 4,
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            RenterId = 4,
                            StartTime = new DateTime(2023, 12, 30, 7, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            BikeId = 4,
                            Duration = new TimeSpan(0, 5, 0, 0, 0),
                            RenterId = 5,
                            StartTime = new DateTime(2023, 12, 31, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            BikeId = 9,
                            Duration = new TimeSpan(0, 6, 0, 0, 0),
                            RenterId = 6,
                            StartTime = new DateTime(2023, 12, 12, 4, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            BikeId = 9,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = 7,
                            StartTime = new DateTime(2023, 12, 17, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            BikeId = 8,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = 8,
                            StartTime = new DateTime(2023, 12, 24, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            BikeId = 6,
                            Duration = new TimeSpan(0, 4, 0, 0, 0),
                            RenterId = 9,
                            StartTime = new DateTime(2023, 12, 21, 7, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            BikeId = 5,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = 10,
                            StartTime = new DateTime(2023, 12, 30, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BikeRental.Domain.Models.Renter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Renter", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Иванов Иван Иванович",
                            Phone = "+7-910-000-0001"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Петров Пётр Петрович",
                            Phone = "+7-910-000-0002"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Сидоров Сидор Сидорович",
                            Phone = "+7-910-000-0003"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Кузнецова Анна Андреевна",
                            Phone = "+7-910-000-0004"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Морозов Дмитрий Сергеевич",
                            Phone = "+7-910-000-0005"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Васильева Ольга Николаевна",
                            Phone = "+7-910-000-0006"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Смирнов Алексей Викторович",
                            Phone = "+7-910-000-0007"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Никитина Мария Ивановна",
                            Phone = "+7-910-000-0008"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Орлов Сергей Павлович",
                            Phone = "+7-910-000-0009"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Белова Екатерина Михайловна",
                            Phone = "+7-910-000-0010"
                        });
                });

            modelBuilder.Entity("BikeRental.Domain.Models.Bike", b =>
                {
                    b.HasOne("BikeRental.Domain.Models.BikeModel", "Model")
                        .WithMany("Bikes")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("BikeRental.Domain.Models.RentalRecord", b =>
                {
                    b.HasOne("BikeRental.Domain.Models.Bike", "Bike")
                        .WithMany("RentalRecords")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeRental.Domain.Models.Renter", "Renter")
                        .WithMany("RentalRecords")
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("BikeRental.Domain.Models.Bike", b =>
                {
                    b.Navigation("RentalRecords");
                });

            modelBuilder.Entity("BikeRental.Domain.Models.BikeModel", b =>
                {
                    b.Navigation("Bikes");
                });

            modelBuilder.Entity("BikeRental.Domain.Models.Renter", b =>
                {
                    b.Navigation("RentalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
