// <auto-generated />
using System;
using BikeRental.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRental.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(BikeRentalDbContext))]
    [Migration("20251205190654_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BikeRental.Domain.Models.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Bike", (string)null);
                });

            modelBuilder.Entity("BikeRental.Domain.Models.BikeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BikeWeight")
                        .HasColumnType("float");

                    b.Property<string>("BrakeType")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("HourlyPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("MaxRiderWeight")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WheelSize")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BikeModel", null, t =>
                        {
                            t.HasCheckConstraint("CK_BikeModels_HourlyPrice", "[HourlyPrice] > 0");

                            t.HasCheckConstraint("CK_BikeModels_MaxRiderWeight", "[MaxRiderWeight] > 0");

                            t.HasCheckConstraint("CK_BikeModels_WheelSize", "[WheelSize] > 0");

                            t.HasCheckConstraint("CK_BikeModels_Year", "[Year] IS NULL OR ([Year] >= 1900 AND [Year] <= 2100)");
                        });
                });

            modelBuilder.Entity("BikeRental.Domain.Models.RentalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BikeId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("RenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("RenterId");

                    b.HasIndex("StartTime");

                    b.ToTable("RentalRecord", null, t =>
                        {
                            t.HasCheckConstraint("CK_RentalRecords_Duration", "[Duration] > '00:00:00'");
                        });
                });

            modelBuilder.Entity("BikeRental.Domain.Models.Renter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Renter", (string)null);
                });

            modelBuilder.Entity("BikeRental.Domain.Models.Bike", b =>
                {
                    b.HasOne("BikeRental.Domain.Models.BikeModel", "Model")
                        .WithMany("Bikes")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("BikeRental.Domain.Models.RentalRecord", b =>
                {
                    b.HasOne("BikeRental.Domain.Models.Bike", "Bike")
                        .WithMany("RentalRecords")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeRental.Domain.Models.Renter", "Renter")
                        .WithMany("RentalRecords")
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("BikeRental.Domain.Models.Bike", b =>
                {
                    b.Navigation("RentalRecords");
                });

            modelBuilder.Entity("BikeRental.Domain.Models.BikeModel", b =>
                {
                    b.Navigation("Bikes");
                });

            modelBuilder.Entity("BikeRental.Domain.Models.Renter", b =>
                {
                    b.Navigation("RentalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
